スクリプトを修正。

diff --git a/dromozoa-memcheck b/dromozoa-memcheck
--- a/dromozoa-memcheck
+++ b/dromozoa-memcheck
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (C) 2016 Tomoyuki Fujimori <moyu@dromozoa.com>
+# Copyright (C) 2016,2018 Tomoyuki Fujimori <moyu@dromozoa.com>
 #
 # This file is part of dromozoa-hook.
 #
@@ -19,14 +19,17 @@
 
 if leaks -h >/dev/null 2>&1
 then
-  here=`expr "x$0" : 'x\(.*[^/]\)//*[^/][^/]*/*$' '|' "x$0" : 'x\(//\)[^/]' '|' "x$0" : 'x\(//\)$' '|' "x$0" : 'x\(/\)' '|' .`
-  here=`(cd "$here" && pwd)`
-  root=`(cd "$here/.." && pwd)`
-  filename=$root/lib/libdromozoa-hook.la
-  if test -f "$filename"
-  then
-    . "$filename"
-    filename=$libdir/$dlname
+  dromozoa_dirname() {
+    expr "x$1" : 'x\(.*[^/]\)//*[^/][^/]*/*$' \
+      '|' "x$1" : 'x\(//\)[^/]' \
+      '|' "x$1" : 'x\(//\)$' \
+      '|' "x$1" : 'x\(/\)' \
+      '|' .
+  }
+
+  dromozoa_memcheck() {
+    filename=$1
+    shift
     if test -f "$filename"
     then
       case x$TMPDIR in
@@ -50,11 +53,21 @@ then
       case x$status1$status2 in
         x00) exit 0;;
       esac
-    else
-      printf 'cannot find %s\n' "$filename" >&2
     fi
+  }
+
+  here=`dromozoa_dirname "$0"`
+  here=`(cd "$here" && pwd)`
+  root=`(cd "$here/.." && pwd)`
+  if test -f "$here/.libs/libdromozoa-hook.dylib"
+  then
+    dromozoa_memcheck "$here/.libs/libdromozoa-hook.dylib" "$@"
+  elif test -f "$root/lib/libdromozoa-hook.la"
+  then
+    . "$root/lib/libdromozoa-hook.la"
+    dromozoa_memcheck "$libdir/$dlname" "$@"
   else
-    printf 'cannot find %s\n' "$filename" >&2
+    echo "cannot find libdromozoa-hook" >&2
   fi
 elif valgrind --version 2>&1
 then
